# Generated by Django 4.2.2 on 2025-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='myvideos/'),
        ),
    ]
